@Library('mylibrary')_
pipeline
{
    agent any
    stages
    {
          stage('continuousdownloads_master')
        {
            steps
            {
                script
                {
                    cicd.newgit("https://github.com/chakriyuvi/mymavenn.git")
                }
            }
        }
        
        stage('continuousbuild_master')
        {
            steps
            {
                script
                {
                    cicd.newmaven()
                }
            }
          }
     } 
 }
